// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/LandingVariationA.tsx": () => import("../components/mockups/LandingVariationA.tsx"),
  "./components/mockups/LandingVariationB.tsx": () => import("../components/mockups/LandingVariationB.tsx")
};
